services:

  mysql:
    image: mysql:8.0
    container_name: homerodoh-mysql
    restart: always

    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: homerodoh

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .

    container_name: homerodoh-api

    environment:
      DB_URL: jdbc:mysql://mysql:3306/homerodoh?createDatabaseIfNotExist=true
      DB_USER: root
      DB_PASSWORD: ""

    ports:
      - "8080:8080"

    depends_on:
      - mysql

volumes:
  mysql_data: